import { environment } from './../../../environments/environment';
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ImovelDTO } from '../model/imovelDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ImovelControllerService {

    protected basePath = environment.basePath;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * get
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<ImovelDTO>;
    public getUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ImovelDTO>>;
    public getUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ImovelDTO>>;
    public getUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ImovelDTO>(`${this.basePath}/portal/imoveis/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listarPorPessoa
     * 
     * @param identificador identificador
     * @param tipoPessoa tipoPessoa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listarPorPessoaUsingGET(identificador: string, tipoPessoa: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ImovelDTO>>;
    public listarPorPessoaUsingGET(identificador: string, tipoPessoa: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ImovelDTO>>>;
    public listarPorPessoaUsingGET(identificador: string, tipoPessoa: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ImovelDTO>>>;
    public listarPorPessoaUsingGET(identificador: string, tipoPessoa: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (identificador === null || identificador === undefined) {
            throw new Error('Required parameter identificador was null or undefined when calling listarPorPessoaUsingGET.');
        }

        if (tipoPessoa === null || tipoPessoa === undefined) {
            throw new Error('Required parameter tipoPessoa was null or undefined when calling listarPorPessoaUsingGET.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (identificador !== undefined && identificador !== null) {
            queryParameters = queryParameters.set('identificador', <any>identificador);
        }
        if (tipoPessoa !== undefined && tipoPessoa !== null) {
            queryParameters = queryParameters.set('tipoPessoa', <any>tipoPessoa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ImovelDTO>>(`${this.basePath}/portal/imoveis/listarPorPessoa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
