/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PessoaDTO { 
    identificador?: string;
    nome?: string;
    tipoPessoa?: PessoaDTO.TipoPessoaEnum;
}
export namespace PessoaDTO {
    export type TipoPessoaEnum = 'FISICA' | 'JURIDICA' | 'RURAL';
    export const TipoPessoaEnum = {
        FISICA: 'FISICA' as TipoPessoaEnum,
        JURIDICA: 'JURIDICA' as TipoPessoaEnum,
        RURAL: 'RURAL' as TipoPessoaEnum
    };
}
